
name: forecasting-exchange-rate
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - torch
  - pip
  - pip:
      - lightning
